@api = http://localhost:1235

GET {{api}}/staffs
###
GET {{api}}/by/1
###
GET {{api}}/secure
Content-Type: application/json

{"orgin":"P"}

###

GET {{api}}/file/all

###

POST {{api}}/file/book
Content-Type: application/json

{
    "corporate":"ZOHO",
    "date":"2025-11-30",
    "role":"Front end Developer",
    "package":5.2,
    "count":5
}

###
PATCH {{api}}/file/edit/Infosys
Content-Type: application/json

{
    "package":30.5,
    "count":40
}

###

DELETE {{api}}/file/del/Capgemini